segmentation_map:
  - ['card1.jpg', 'card1_sam.png']
  
# true_dimensions:
#   - [1, 1, 1]
#   - [-1, 1, 1]
#   - [-1, -1, 1]
#   - [-1, -1, -1]
#   - [1, -1, -1]
#   - [1, 1, -1]
  # - [1, -1, 1]

# 6.5, 6.5, 11.6
true_dimensions:
  - [6.5, 6.5, 11.6]
  - [0, 6.5, 11.6]
  - [0, 0, 11.6]
  - [0, 0, 0]
  - [6.5, 0, 0]
  - [6.5, 6.5, 0]
  - [6.5, 0, 11.6]