segmentation_map:
  - ['card1.jpg', 'card1_sam.png']
  - ['mosaic1.jpg', '_mosaic1.png']

image_w_labels:  # (label, image name (./demo/{filename}))
  - ['dummy', 'DLT.jpg']
  
# true_dimensions:
#   - [1, 1, 1]
#   - [-1, 1, 1]
#   - [-1, -1, 1]
#   - [-1, -1, -1]
#   - [1, -1, -1]
#   - [1, 1, -1]
  # - [1, -1, 1]

true_dimensions:
  - [6.5, 6.5, 11.6]
  - [0, 6.5, 11.6]
  - [0, 0, 11.6]
  - [0, 0, 0]
  - [6.5, 0, 0]
  - [6.5, 6.5, 0]
  - [6.5, 0, 11.6]